# -*- coding: utf-8 -*-
"""dijkstraflow11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zly1-4D1z5qhNHTJkVmlqiEZUIWWgglg
"""

#!/usr/bin/env python
"""
Ryu controller that discovers topology and, when a data flow is added,
computes up to 3 disjoint shortest paths for that flow using a modified Dijkstra's algorithm.
The algorithm considers link costs and only allows links with sufficient available bandwidth.
The computed flow paths (with their costs and delays) are logged into a text file,
and the topology (with link costs and available bandwidth) is plotted.
Only links defined in link_costs.txt are added.
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import random
import networkx as nx
import time

from ryu.base import app_manager
from ryu.controller import ofp_event
from ryu.controller.handler import CONFIG_DISPATCHER, MAIN_DISPATCHER, set_ev_cls
from ryu.ofproto import ofproto_v1_3

from ryu.lib import hub
from ryu.lib.packet import packet, ethernet

from ryu.topology import event
from ryu.topology import switches


class DijkstraController(app_manager.RyuApp):
    OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]
    # Delay factor (in ms) per unit cost
    DELAY_PER_HOP = 10
    # Default total bandwidth for a link (can be adjusted or loaded from a file)
    DEFAULT_BANDWIDTH = 1000

    def __init__(self, *args, **kwargs):
        super(DijkstraController, self).__init__(*args, **kwargs)
        # The network topology graph (nodes can be switches or hosts)
        self.net = nx.Graph()
        hub.sleep(5)
        # Mapping for hosts: MAC -> (switch_dpid, port)
        self.hosts = {}
        # Mapping for switch-to-switch links: (src_dpid, dst_dpid) -> out_port
        self.link_ports = {}
        # Load cost mapping from file
        self.link_costs = {}
        self.load_link_costs()
        hub.sleep(5)
        # Monitor and plotting history for available bandwidth
        self.monitor_count = 0
        self.available_bw_history = []
        self.monitor_history = []
        # Attribute for tracking average path cost over time
        self.avg_path_cost_history = []
        # Track active flows with their creation cycle.
        self.active_flows = []
        # NEW: Record a history of all flows for plotting purposes.
        self.flow_history = []
        # Start a monitoring thread that updates plots and adds random flows periodically.
        self.monitor_thread = hub.spawn(self._monitor)

    def _monitor(self):
        """
        Periodically update the topology, available bandwidth plot, average path cost plot,
        and the box plots for flow costs and bandwidth usage.
        Also, add random data flows and remove expired flows.
        """
        while True:
            self.monitor_count += 1

            # === Expire flows older than 5 monitor cycles ===
            expired_flows = []
            for flow in self.active_flows:
                if self.monitor_count - flow["creation_cycle"] >= 5:
                    # Restore the consumed bandwidth along the flow's path.
                    for i in range(len(flow["primary_path"]) - 1):
                        u = flow["primary_path"][i]
                        v = flow["primary_path"][i + 1]
                        self.net[u][v]['available_bw'] += flow["flow_bw"]
                        # Do not exceed the total bandwidth.
                        if self.net[u][v]['available_bw'] > self.net[u][v]['bandwidth']:
                            self.net[u][v]['available_bw'] = self.net[u][v]['bandwidth']
                    expired_flows.append(flow)
            for flow in expired_flows:
                self.active_flows.remove(flow)
            # ==================================================

            total_avail_bw = sum(data.get('available_bw', 0)
                                 for _, _, data in self.net.edges(data=True))
            self.available_bw_history.append(total_avail_bw)
            self.monitor_history.append(self.monitor_count)

            self.plot_topology()
            self.plot_available_bw_over_time()

            self.current_cycle_costs = []
            nodes = list(self.net.nodes())
            if len(nodes) >= 2:
                for _ in range(10):
                    src, dst = random.sample(nodes, 2)
                    flow_bw = random.randint(100, 300)
                    self.add_data_flow(src, dst, flow_bw)

            if self.current_cycle_costs:
                avg_cost = sum(self.current_cycle_costs) / len(self.current_cycle_costs)
            else:
                avg_cost = 0
            self.avg_path_cost_history.append(avg_cost)
            self.plot_avg_path_cost_over_time()

            # NEW: Plot box plots for flow costs and bandwidth usage.
            self.plot_cost_boxplot()
            self.plot_bandwidth_boxplot()
            self.plot_combined()

            hub.sleep(5)

    def compute_flow_path(self, src, dst, flow_bw):
        """
        Compute up to 3 disjoint paths for a data flow from src to dst considering available bandwidth.
        Only links with available bandwidth >= flow_bw are allowed.
        Each path's cost is the sum of link weights and the delay is DELAY_PER_HOP * cost.
        The computed paths are appended to 'shortest_paths.txt'.
        Returns a list of tuples (path, cost, delay).
        """
        def weight_func(u, v, d):
            # Only allow links that have enough available bandwidth.
            if d.get('available_bw', 0) < flow_bw:
                return float('inf')
            return d.get('weight', float('inf'))

        disjoint_paths = []
        temp_net = self.net.copy()
        for path_index in range(3):
            try:
                path = nx.dijkstra_path(temp_net, src, dst, weight=weight_func)
                cost = nx.dijkstra_path_length(temp_net, src, dst, weight=weight_func)
                delay = cost * self.DELAY_PER_HOP
                disjoint_paths.append((path, cost, delay))
                # Remove edges in the found path to ensure disjointness in subsequent paths.
                for i in range(len(path) - 1):
                    if temp_net.has_edge(path[i], path[i+1]):
                        temp_net.remove_edge(path[i], path[i+1])
            except nx.NetworkXNoPath:
                break

        if not disjoint_paths:
            self.logger.info("No available disjoint paths from %s to %s with required bandwidth %d",
                             src, dst, flow_bw)
            return None

        with open("shortest_paths.txt", "a") as f:
            for idx, (path, cost, delay) in enumerate(disjoint_paths):
                f.write("Flow from {} to {} (Path {}): Path: {} | Cost: {} | Delay: {} ms | Bandwidth used: {} \n".format(
                    src, dst, idx+1, path, cost, delay, flow_bw))
        return disjoint_paths

    def load_link_costs(self):
        """
        Load link costs from the file 'link_costs.txt'.
        Each line should have: <src> <dst> <cost>
        Switch names are assumed to be of the form 's<ID>'.
        """
        self.link_costs = {}
        try:
            with open('link_costs.txt', 'r') as f:
                for line in f:
                    src, dst, cost = line.strip().split()
                    # Convert switch names like 's1' to integer IDs.
                    src_id = int(src[1:])
                    dst_id = int(dst[1:])
                    key = frozenset({src_id, dst_id})
                    self.link_costs[key] = int(cost)
            self.logger.info("Loaded link costs: %s", self.link_costs)
        except Exception as e:
            self.logger.error("Failed to load link_costs.txt: %s", e)

    def plot_topology(self):
        """
        Plot the current network topology (nodes and links) and save to a PNG file.
        The plot shows link costs and available bandwidth as edge labels.
        Additionally, it displays the number of active data flows.
        """
        plt.figure(figsize=(10, 10))
        pos = nx.spring_layout(self.net, seed=42)
        node_size = 100  # smaller nodes

        # Label nodes (assumed to be integers for switches).
        labels = {node: str(node) for node in self.net.nodes()}

        nx.draw_networkx_nodes(self.net, pos, node_color='lightblue', node_size=node_size)
        nx.draw_networkx_labels(self.net, pos, labels=labels, font_size=8)

        # Compute edge colors based on available bandwidth.
        edge_colors = []
        for u, v, data in self.net.edges(data=True):
            avail_bw = data.get('available_bw', 0)
            normalized = avail_bw / self.DEFAULT_BANDWIDTH  # between 0 and 1
            color = (1 - normalized, normalized, 0)
            edge_colors.append(color)

        nx.draw_networkx_edges(self.net, pos, edgelist=list(self.net.edges()),
                              edge_color=edge_colors, width=2)

        # Add a text box displaying the number of active flows.
        active_flow_count = len(self.active_flows)
        plt.text(0.05, 0.95, f"Active Flows: {active_flow_count}",
                transform=plt.gca().transAxes,
                fontsize=12, verticalalignment='top',
                bbox=dict(facecolor='white', alpha=0.8, boxstyle='round'))

        plt.title("Network Topology with Available Bandwidth")
        plt.tight_layout()
        plt.savefig("topology.png")
        plt.close()
        self.logger.info("Topology plot saved as topology.png")

    def plot_available_bw_over_time(self):
        """
        Plot a time series of the total available bandwidth over monitor interactions.
        """
        plt.figure(figsize=(8, 6))
        plt.plot(self.monitor_history, self.available_bw_history, marker='o', linestyle='-')
        plt.xlabel("Monitor Interaction Count")
        plt.ylabel("Total Available Bandwidth")
        plt.title("Available Bandwidth over Monitor Interactions")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("available_bw_over_time.png")
        plt.close()
        self.logger.info("Available Bandwidth over time plot saved as available_bw_over_time.png")

    def plot_avg_path_cost_over_time(self):
        """
        Plot a time series of the average path cost for used data flows over monitor interactions.
        """
        plt.figure(figsize=(8, 6))
        plt.plot(self.monitor_history, self.avg_path_cost_history, marker='o', linestyle='-', color="green")
        plt.xlabel("Monitor Interaction Count")
        plt.ylabel("Average Path Cost")
        plt.title("Average Path Cost over Monitor Interactions")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("avg_path_cost_over_time.png")
        plt.close()
        self.logger.info("Average Path Cost over time plot saved as avg_path_cost_over_time.png")

    def plot_cost_boxplot(self):
        """
        Create a box plot for the costs of data flows using all flow history.
        """
        if not self.flow_history:
            return
        # Extract all non-None cost values.
        costs = [flow["cost"] for flow in self.flow_history if flow["cost"] is not None]
        if not costs:
            return
        plt.figure(figsize=(8, 6))
        plt.boxplot(costs)
        plt.ylabel("Flow Costs")
        plt.title("Box Plot of Data Flow Costs")
        plt.tight_layout()
        plt.savefig("flow_cost_boxplot.png")
        plt.close()
        self.logger.info("Flow cost box plot saved as flow_cost_boxplot.png")

    def plot_bandwidth_boxplot(self):
        """
        Create a box plot for the bandwidth used by data flows using all flow history.
        """
        if not self.flow_history:
            return
        bandwidths = [flow["flow_bw"] for flow in self.flow_history]
        if not bandwidths:
            return
        plt.figure(figsize=(8, 6))
        plt.boxplot(bandwidths)
        plt.ylabel("Bandwidth Used")
        plt.title("Box Plot of Data Flow Bandwidth")
        plt.tight_layout()
        plt.savefig("flow_bandwidth_boxplot.png")
        plt.close()
        self.logger.info("Flow bandwidth box plot saved as flow_bandwidth_boxplot.png")

    def plot_combined(self):
        """
        Plot available bandwidth, average path cost, flow cost boxplot,
        and flow bandwidth boxplot on one figure (2x2 grid) and save as combined_plots.png.
        """
        fig, axs = plt.subplots(2, 2, figsize=(12, 10))

        # Plot Available Bandwidth over Monitor Interactions
        axs[0, 0].plot(self.monitor_history, self.available_bw_history, marker='o', linestyle='-')
        axs[0, 0].set_xlabel("Monitor Interaction Count")
        axs[0, 0].set_ylabel("Total Available Bandwidth")
        axs[0, 0].set_title("Available Bandwidth over Time")
        axs[0, 0].grid(True)

        # Plot Average Path Cost over Monitor Interactions
        axs[0, 1].plot(self.monitor_history, self.avg_path_cost_history, marker='o', linestyle='-', color="green")
        axs[0, 1].set_xlabel("Monitor Interaction Count")
        axs[0, 1].set_ylabel("Average Path Cost")
        axs[0, 1].set_title("Average Path Cost over Time")
        axs[0, 1].grid(True)

        # Plot Box Plot for Flow Costs
        if self.flow_history:
            costs = [flow["cost"] for flow in self.flow_history if flow["cost"] is not None]
            if costs:
                axs[1, 1].boxplot(costs)
                axs[1, 1].grid(True)
                axs[1, 1].set_ylabel("Flow Costs")
                axs[1, 1].set_title("Flow Cost Box Plot")
            else:
                axs[1, 1].text(0.5, 0.5, 'No cost data', horizontalalignment='center')
        else:
            axs[1, 1].text(0.5, 0.5, 'No flow history', horizontalalignment='center')

        # Plot Box Plot for Flow Bandwidth Usage
        if self.flow_history:
            bandwidths = [flow["flow_bw"] for flow in self.flow_history]
            if bandwidths:
                axs[1, 0].boxplot(bandwidths)
                axs[1, 0].grid(True)
                axs[1, 0].set_ylabel("Bandwidth Used")
                axs[1, 0].set_title("Flow Bandwidth Box Plot")
            else:
                axs[1, 0].text(0.5, 0.5, 'No bandwidth data', horizontalalignment='center')
        else:
            axs[1, 0].text(0.5, 0.5, 'No flow history', horizontalalignment='center')

        plt.tight_layout()
        plt.savefig("combined_plots.png")
        plt.close()
        self.logger.info("Combined plot saved as combined_plots.png")

    def add_data_flow(self, src, dst, flow_bw):
        """
        Simulate adding a new data flow from source to destination that consumes bandwidth.
        Record the flow along with the monitor cycle it was created.
        Now, compute three disjoint paths and use the first one as the primary path.
        """
        paths = self.compute_flow_path(src, dst, flow_bw)
        if not paths:
            return

        # Use the first (shortest) path as the primary path.
        primary_path, cost, delay = paths[0]
        if cost is not None and hasattr(self, 'current_cycle_costs'):
            self.current_cycle_costs.append(cost)

        # Update available bandwidth along the chosen primary path.
        for i in range(len(primary_path) - 1):
            u = primary_path[i]
            v = primary_path[i + 1]
            self.net[u][v]['available_bw'] -= flow_bw
            if self.net[u][v]['available_bw'] < 0:
                self.net[u][v]['available_bw'] = 0

        # Record the active flow with its creation cycle, including all computed disjoint paths.
        flow_record = {
            "src": src,
            "dst": dst,
            "flow_bw": flow_bw,
            "primary_path": primary_path,
            "disjoint_paths": paths,
            "creation_cycle": self.monitor_count,
            "cost": cost,
            "delay": delay
        }
        self.active_flows.append(flow_record)
        # NEW: Also save a copy in the overall flow history.
        self.flow_history.append(flow_record.copy())

    @set_ev_cls(event.EventSwitchEnter)
    def switch_enter_handler(self, ev):
        """
        When a new switch enters the network, add its datapath ID as a node.
        """
        for sw in ev.switches:
            dpid = sw.dp.id
            if not self.net.has_node(dpid):
                self.net.add_node(dpid)
                self.logger.info("Switch %s entered.", dpid)

    @set_ev_cls(event.EventLinkAdd)
    def link_add_handler(self, ev):
        """
        When a link is discovered, add an undirected edge between the two switches only if the link
        is defined in link_costs.txt. The edge is annotated with its cost, total bandwidth, and available bandwidth.
        """
        link = ev.link
        src_dpid = link.src.dpid
        dst_dpid = link.dst.dpid
        key = frozenset({src_dpid, dst_dpid})
        if key not in self.link_costs:
            return

        if not self.net.has_node(src_dpid):
            self.net.add_node(src_dpid)
        if not self.net.has_node(dst_dpid):
            self.net.add_node(dst_dpid)

        cost = self.link_costs[key]
        self.net.add_edge(src_dpid, dst_dpid, weight=cost,
                          bandwidth=self.DEFAULT_BANDWIDTH,
                          available_bw=self.DEFAULT_BANDWIDTH)
        # For an undirected graph, add port mapping in both directions.
        self.link_ports[(src_dpid, dst_dpid)] = link.src.port_no
        self.link_ports[(dst_dpid, src_dpid)] = link.dst.port_no

    @set_ev_cls(ofp_event.EventOFPSwitchFeatures, CONFIG_DISPATCHER)
    def switch_features_handler(self, ev):
        """
        Install the table-miss flow entry so that packets are sent to the controller
        (to learn host locations).
        """
        datapath = ev.msg.datapath
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser

        match = parser.OFPMatch()
        actions = [parser.OFPActionOutput(ofproto.OFPP_CONTROLLER, ofproto.OFPCML_NO_BUFFER)]
        inst = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS, actions)]
        mod = parser.OFPFlowMod(datapath=datapath, priority=0,
                                match=match, instructions=inst)
        datapath.send_msg(mod)

    @set_ev_cls(ofp_event.EventOFPPacketIn, MAIN_DISPATCHER)
    def packet_in_handler(self, ev):
        """
        Handle incoming packets:
         - Learn hosts and add them to the topology graph.
         - If the destination host is known, compute a shortest path using the base graph.
         - Forward the packet along the computed path or flood if unknown.
        """
        msg = ev.msg
        datapath = msg.datapath
        dpid = datapath.id
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser

        in_port = msg.match['in_port']

        pkt = packet.Packet(msg.data)
        eth = pkt.get_protocol(ethernet.ethernet)
        if eth is None:
            return

        src_mac = eth.src
        dst_mac = eth.dst

        if dst_mac in self.hosts:
            dest_switch, dest_port = self.hosts[dst_mac]
            try:
                path = nx.dijkstra_path(self.net, dpid, dest_switch, weight='weight')
                self.logger.info("Computed path from %s to %s: %s", dpid, dest_switch, path)
                if len(path) > 1:
                    next_hop = path[1]
                    out_port = self.link_ports.get((dpid, next_hop), ofproto.OFPP_FLOOD)
                else:
                    out_port = dest_port
            except nx.NetworkXNoPath:
                self.logger.info("No path from switch %s to host %s; flooding", dpid, dst_mac)
                out_port = ofproto.OFPP_FLOOD
        else:
            out_port = ofproto.OFPP_FLOOD

        actions = [parser.OFPActionOutput(out_port)]
        out = parser.OFPPacketOut(datapath=datapath, buffer_id=msg.buffer_id,
                                  in_port=in_port, actions=actions, data=msg.data)
        datapath.send_msg(out)

