# -*- coding: utf-8 -*-
"""multipath55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11SmMJIzDeVeP3G276Ur9lBHU1fNshx7y
"""

#!/usr/bin/env python
"""
Ryu controller that discovers topology and, when a data flow is added,
computes up to 3 disjoint shortest paths for that flow.
You can choose between different path-computation methods:
    - Modified Dijkstra (iterative edge removal)
    - Yen's algorithm
    - A simplified Suurballe algorithm
    - Edge disjoint shortest pair algorithm (computing a disjoint pair plus an extra disjoint path)
    - Bellman-Ford algorithm (iterative disjoint paths using Bellman-Ford)
    - k-shortest paths algorithm by David Eppstein
The algorithm considers link costs and only allows links with sufficient available bandwidth.
The computed flow paths (with their costs and delays) are logged into a text file,
and the topology (with link costs and available bandwidth) is plotted.
Only links defined in link_costs.txt are added.
"""

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import random
random.seed(42)
import math
import networkx as nx
import time
import psutil

from ryu.base import app_manager
from ryu.controller import ofp_event
from ryu.controller.handler import CONFIG_DISPATCHER, MAIN_DISPATCHER, set_ev_cls
from ryu.ofproto import ofproto_v1_3

from ryu.lib import hub
from ryu.lib.packet import packet, ethernet

from ryu.topology import event
from ryu.topology import switches


class DijkstraController(app_manager.RyuApp):
    OFP_VERSIONS = [ofproto_v1_3.OFP_VERSION]
    # Delay factor (in ms) per unit cost.
    DELAY_PER_HOP = 10
    # Default 50000
    # DragonFly 3000
    # FatTree 5000
    # JellyFish 24000
    DEFAULT_BANDWIDTH = 500

    def __init__(self, *args, **kwargs):
        super(DijkstraController, self).__init__(*args, **kwargs)
        # How many logical CPUs we have; 100% means “all of these fully busy”
        self.cpu_count = psutil.cpu_count(logical=True)
        # Total physical RAM (in bytes)
        self.total_ram = psutil.virtual_memory().total
        # The network topology graph (nodes can be switches or hosts)
        self.net = nx.Graph()
        hub.sleep(20)
        # Mapping for hosts: MAC -> (switch_dpid, port)
        self.hosts = {}
        # Mapping for switch-to-switch links: (src_dpid, dst_dpid) -> out_port
        self.link_ports = {}
        # Load cost mapping from file.
        self.link_costs = {}
        self.load_link_costs()
        hub.sleep(20)
        # Monitoring and plotting history.
        self.monitor_count = 0
        self.available_bw_history = []
        self.monitor_history = []
        self.link_bw_cycle_history = []
        self.avg_path_cost_history = []
        # New: tracking failed path counts
        self.failed_path_count_history = []
        # Active flows and overall flow history.
        self.active_flows = []
        self.flow_history = []
        # Set the algorithm to use.
        # Options: "dijkstra", "yen", "suurballe", "edge_disjoint", "bellman_ford", "eppstein"
        self.path_algorithm = "dijkstra"  # Change as desired.
        # Start a monitoring thread.
        self.monitor_thread = hub.spawn(self._monitor)
        # Initialize/clear the stats file, and write a header + max‐capacity line
        with open("monitor_stats.txt", "w") as f:
            f.write("Cycle | Duration (s) | CPU% | RAM%\n")
            f.write(f"Max   |       —      | 100% = {self.cpu_count}× fully busy | "
                    f"100% = {self.total_ram / (1024**3):.2f} GB total\n\n")

    def _monitor(self):
        """
        Periodically update topology, plots, and add random data flows.
        Also, expire flows older than 5 monitor cycles.
        """
        while self.monitor_count < 25:
            self.monitor_count += 1
            cycle_start = time.time()
            # Initialize failure counter for this cycle
            self.current_cycle_failures = 0

            # === Expire flows older than 5 cycles ===
            expired_flows = []
            for flow in self.active_flows:
                if self.monitor_count - flow["creation_cycle"] >= 5:
                    # restore consumed bandwidth along each of the 3 disjoint paths
                    for path, cost, delay in flow["disjoint_paths"][:3]:
                        for u, v in zip(path, path[1:]):
                            # add back, but don’t exceed the link’s capacity
                            self.net[u][v]['available_bw'] = min(
                                self.net[u][v]['available_bw'] + flow["flow_bw"],
                                self.net[u][v]['bandwidth']
                            )
                    expired_flows.append(flow)
            for flow in expired_flows:
                self.active_flows.remove(flow)
            # =====================================================

            total_avail_bw = sum(data.get('available_bw', 0) for _, _, data in self.net.edges(data=True))
            self.available_bw_history.append(total_avail_bw)
            self.monitor_history.append(self.monitor_count)

            current_link_bws = [data.get('available_bw', 0)
                                      for u, v, data in self.net.edges(data=True)]
            self.link_bw_cycle_history.append(current_link_bws)

            self.plot_topology()
            self.plot_available_bw_over_time()

            self.current_cycle_costs = []
            nodes = list(self.net.nodes())
            if len(nodes) >= 2:
                for _ in range(250):
                    src, dst = random.sample(nodes, 2)
                    flow_bw = random.randint(1, 10)
                    self.add_data_flow(src, dst, flow_bw)

            # Record failure count history
            self.failed_path_count_history.append(self.current_cycle_failures)

            if self.current_cycle_costs:
                avg_cost = sum(self.current_cycle_costs) / len(self.current_cycle_costs)
            else:
                avg_cost = 0
            self.avg_path_cost_history.append(avg_cost)
            self.plot_avg_path_cost_over_time()

            self.plot_cost_boxplot()
            self.plot_bandwidth_boxplot()
            # New: plot failures separately
            self.plot_failed_paths_over_time()
            self.plot_link_bw_boxplot()
            self.plot_link_bw_per_cycle()
            self.plot_avg_costs_by_path_index()
            # Updated combined plot to include failures
            self.plot_combined()

            hub.sleep(5)

            # record end-of-cycle timing and resource usage
            cycle_end = time.time()
            duration = cycle_end - cycle_start
            cpu = psutil.cpu_percent(interval=0.1)
            mem = psutil.virtual_memory().percent

            # append to the same stats file
            self.log_cycle_stats(self.monitor_count, duration, cpu, mem)

            self.logger.info(
                "Monitor cycle %d took %.3fs, CPU: %.1f%%, RAM: %.1f%%",
                self.monitor_count, duration, cpu, mem)


    def log_cycle_stats(self, cycle, duration, cpu, mem):
        """
        Append a line to monitor_stats.txt with:
          Cycle number | duration in seconds | CPU% | RAM%
        """
        with open("monitor_stats.txt", "a") as f:
            f.write(f"{cycle:5d} | {duration:10.3f} | {cpu:5.1f}% | {mem:5.1f}%\n")

    def compute_flow_path(self, src, dst, flow_bw):
        """
        Dispatch the flow path computation to the chosen algorithm.
        Returns up to 3 paths (each a tuple: (path, cost, delay)).
        """
        if self.path_algorithm == "yen":
            return self.compute_flow_path_yen(src, dst, flow_bw)
        elif self.path_algorithm == "suurballe":
            return self.compute_flow_path_suurballe(src, dst, flow_bw)
        elif self.path_algorithm == "edge_disjoint":
            return self.compute_flow_path_edge_disjoint(src, dst, flow_bw)
        elif self.path_algorithm == "bellman_ford":
            return self.compute_flow_path_bellman_ford(src, dst, flow_bw)
        elif self.path_algorithm == "eppstein":    # New option.
            return self.compute_flow_path_eppstein(src, dst, flow_bw)
        else:
            return self.compute_flow_path_dijkstra(src, dst, flow_bw)

    def compute_flow_path_dijkstra(self, src, dst, flow_bw):
        """
        Compute up to 3 disjoint paths using a modified Dijkstra algorithm.
        A temporary graph copy is used and, after finding a path,
        its edges are removed to enforce disjointness.
        """
        def weight_func(u, v, d):
            if d.get('available_bw', 0) < flow_bw:
                return float('inf')
            return d.get('weight', float('inf'))

        disjoint_paths = []
        temp_net = self.net.copy()
        for _ in range(3):
            try:
                path = nx.dijkstra_path(temp_net, src, dst, weight=weight_func)
                cost = nx.dijkstra_path_length(temp_net, src, dst, weight=weight_func)
                delay = cost * self.DELAY_PER_HOP
                disjoint_paths.append((path, cost, delay))
                # Remove edges in the found path.
                for i in range(len(path)-1):
                    if temp_net.has_edge(path[i], path[i+1]):
                        temp_net.remove_edge(path[i], path[i+1])
            except nx.NetworkXNoPath:
                break

        if not disjoint_paths:
            self.logger.info("No available disjoint paths from %s to %s with bandwidth %d",
                             src, dst, flow_bw)
            return None

        with open("shortest_paths.txt", "a") as f:
            for idx, (path, cost, delay) in enumerate(disjoint_paths):
                f.write("Flow from {} to {} (Dijkstra Path {}): {} | Cost: {} | Delay: {} ms | Bandwidth: {} \n".format(
                    src, dst, idx+1, path, cost, delay, flow_bw))
        return disjoint_paths

    def compute_flow_path_yen(self, src, dst, flow_bw):
        """
        Compute exactly 3 fully edge‐disjoint paths using Yen’s k‐shortest simple‐paths,
        by removing each found path’s edges before computing the next.
        Returns [(path, cost, delay), …] or None if fewer than 3 exist.
        """
        try:
            temp = self.net.copy()
            disjoint_paths = []

            for _ in range(3):
                # build a bandwidth‐pruned view of temp
                H = nx.Graph()
                for u, v, data in temp.edges(data=True):
                    if data.get('available_bw', 0) >= flow_bw:
                        H.add_edge(u, v, weight=data['weight'])

                # try to get the next‐shortest simple path
                try:
                    p = next(nx.shortest_simple_paths(H, src, dst, weight='weight'))
                except (nx.NetworkXNoPath, StopIteration):
                    break

                cost = sum(H[u][v]['weight'] for u, v in zip(p, p[1:]))
                delay = cost * self.DELAY_PER_HOP
                disjoint_paths.append((p, cost, delay))

                # remove those edges from temp to enforce disjointness
                for u, v in zip(p, p[1:]):
                    if temp.has_edge(u, v):
                        temp.remove_edge(u, v)

            if len(disjoint_paths) < 3:
                return None

            with open("shortest_paths.txt", "a") as f:
                for idx, (p, c, d) in enumerate(disjoint_paths, start=1):
                    f.write(f"Flow from {src} to {dst} (Yen Path {idx}): {p} | "
                            f"Cost: {c} | Delay: {d} ms | BW: {flow_bw}\n")

            return disjoint_paths

        except Exception as e:
            self.logger.error("Yen error %s→%s (bw=%d): %s", src, dst, flow_bw, e)
            return None

    def compute_flow_path_suurballe(self, src, dst, flow_bw):
        """
        Compute up to 3 edge-disjoint paths using Suurballe's algorithm.
        """
        try:
            # Build directed subgraph H with only edges that can carry the flow
            H = nx.DiGraph()
            for u, v, data in self.net.edges(data=True):
                if data.get('available_bw', 0) >= flow_bw:
                    w = data.get('weight', float('inf'))
                    H.add_edge(u, v, weight=w)
                    H.add_edge(v, u, weight=w)

            # Early exit if no path exists
            if not nx.has_path(H, src, dst):
                self.logger.info("No available Suurballe paths from %s to %s (bw=%d)", src, dst, flow_bw)
                return None

            # Primary shortest path
            path1 = nx.dijkstra_path(H, src, dst, weight='weight')
            cost1 = nx.dijkstra_path_length(H, src, dst, weight='weight')

            # Reweight edges
            dist = nx.single_source_dijkstra_path_length(H, src, weight='weight')
            H_r = nx.DiGraph()
            for u, v, d in H.edges(data=True):
                if u in dist and v in dist:
                    new_w = d['weight'] + dist[u] - dist[v]
                    H_r.add_edge(u, v, weight=new_w)

            # Remove both directions of path1 from H_r to enforce edge-disjointness
            for u, v in zip(path1, path1[1:]):
                if H_r.has_edge(u, v):
                    H_r.remove_edge(u, v)
                if H_r.has_edge(v, u):
                    H_r.remove_edge(v, u)

            # Second shortest path in residual
            try:
                path2 = nx.dijkstra_path(H_r, src, dst, weight='weight')
                # Compute real cost on original H
                cost2 = sum(H[path2[i]][path2[i+1]]['weight'] for i in range(len(path2)-1))
            except nx.NetworkXNoPath:
                path2, cost2 = None, None

            suurballe_paths = [(path1, cost1, cost1 * self.DELAY_PER_HOP)]
            if path2 is not None:
                suurballe_paths.append((path2, cost2, cost2 * self.DELAY_PER_HOP))

            # Third path: simple disjoint by removing both directions of first two paths
            temp = self.net.copy()
            for p in [path1] + ([path2] if path2 else []):
                for u, v in zip(p, p[1:]):
                    if temp.has_edge(u, v): temp.remove_edge(u, v)
                    if temp.has_edge(v, u): temp.remove_edge(v, u)

            def wf(u, v, d):
                return d['weight'] if d.get('available_bw', 0) >= flow_bw else float('inf')

            try:
                path3 = nx.dijkstra_path(temp, src, dst, weight=wf)
                cost3 = nx.dijkstra_path_length(temp, src, dst, weight=wf)
                suurballe_paths.append((path3, cost3, cost3 * self.DELAY_PER_HOP))
            except nx.NetworkXNoPath:
                pass

            if not suurballe_paths:
                self.logger.info(
                    "No valid Suurballe paths from %s to %s (bw=%d)", src, dst, flow_bw
                )
                return None

            # Log and return
            with open("shortest_paths.txt", "a") as f:
                for idx, (p, c, d) in enumerate(suurballe_paths, start=1):
                    f.write(
                        f"Suurballe from {src} to {dst} (Path {idx}): {p} | "
                        f"Cost: {c} | Delay: {d} ms | Bandwidth: {flow_bw}\n"
                    )
            return suurballe_paths

        except Exception as e:
            self.logger.error(
                "Error computing Suurballe paths from %s to %s (bw=%d): %s",
                src, dst, flow_bw, e
            )
            return None

    def compute_flow_path_edge_disjoint(self, src, dst, flow_bw):
        """
        Compute up to 3 disjoint paths using an edge‐disjoint approach,
        pre‐filtering by bandwidth and catching errors to continue execution.
        """
        try:
            # Build pruned graph G with only edges that can carry the flow
            G = nx.Graph()
            for u, v, data in self.net.edges(data=True):
                if data.get('available_bw', 0) >= flow_bw:
                    G.add_edge(u, v, weight=data.get('weight', float('inf')))

            # Early exit if no path exists
            if not nx.has_path(G, src, dst):
                self.logger.info(
                    "No available edge‐disjoint paths from %s to %s (bw=%d)",
                    src, dst, flow_bw
                )
                return None

            paths = []
            # Path 1
            path1 = nx.dijkstra_path(G, src, dst, weight='weight')
            cost1 = nx.dijkstra_path_length(G, src, dst, weight='weight')
            delay1 = cost1 * self.DELAY_PER_HOP
            paths.append((path1, cost1, delay1))

            # Path 2: remove path1 edges
            G2 = G.copy()
            for u, v in zip(path1, path1[1:]):
                if G2.has_edge(u, v):
                    G2.remove_edge(u, v)
            try:
                path2 = nx.dijkstra_path(G2, src, dst, weight='weight')
                cost2 = nx.dijkstra_path_length(G2, src, dst, weight='weight')
                delay2 = cost2 * self.DELAY_PER_HOP
                paths.append((path2, cost2, delay2))
            except nx.NetworkXNoPath:
                path2 = None

            # Path 3: remove path2 edges too
            G3 = G2.copy()
            if path2:
                for u, v in zip(path2, path2[1:]):
                    if G3.has_edge(u, v):
                        G3.remove_edge(u, v)
            try:
                path3 = nx.dijkstra_path(G3, src, dst, weight='weight')
                cost3 = nx.dijkstra_path_length(G3, src, dst, weight='weight')
                delay3 = cost3 * self.DELAY_PER_HOP
                paths.append((path3, cost3, delay3))
            except nx.NetworkXNoPath:
                pass

            # Log and return
            with open("shortest_paths.txt", "a") as f:
                for idx, (p, c, d) in enumerate(paths, start=1):
                    f.write(
                        f"Edge-Disjoint from {src} to {dst} (Path {idx}): {p} | "
                        f"Cost: {c} | Delay: {d} ms | Bandwidth: {flow_bw}\n"
                    )
            return paths

        except Exception as e:
            self.logger.error(
                "Error computing edge‐disjoint paths from %s to %s (bw=%d): %s",
                src, dst, flow_bw, e
            )
            return None

    def compute_flow_path_bellman_ford(self, src, dst, flow_bw):
        """
        Compute up to 3 disjoint paths using the Bellman-Ford algorithm.
        A temporary graph copy is used and, after finding a path,
        its edges are removed to enforce disjointness.
        """
        def weight_func(u, v, d):
            if d.get('available_bw', 0) < flow_bw:
                return float('inf')
            return d.get('weight', float('inf'))

        disjoint_paths = []
        temp_net = self.net.copy()
        for _ in range(3):
            try:
                path = nx.bellman_ford_path(temp_net, src, dst, weight=weight_func)
                cost = nx.bellman_ford_path_length(temp_net, src, dst, weight=weight_func)
                delay = cost * self.DELAY_PER_HOP
                disjoint_paths.append((path, cost, delay))
                for i in range(len(path)-1):
                    if temp_net.has_edge(path[i], path[i+1]):
                        temp_net.remove_edge(path[i], path[i+1])
            except nx.NetworkXNoPath:
                break

        if not disjoint_paths:
            self.logger.info("No available disjoint paths from %s to %s with bandwidth %d (Bellman-Ford)",
                             src, dst, flow_bw)
            return None

        with open("shortest_paths.txt", "a") as f:
            for idx, (path, cost, delay) in enumerate(disjoint_paths):
                f.write("Flow from {} to {} (Bellman-Ford Path {}): {} | Cost: {} | Delay: {} ms | Bandwidth: {} \n".format(
                    src, dst, idx+1, path, cost, delay, flow_bw))
        return disjoint_paths

    def compute_flow_path_eppstein(self, src, dst, flow_bw):
        """
        Compute exactly 3 fully edge‐disjoint paths using an iterative
        k‐shortest simple paths approach, removing each found path’s edges.
        Returns [(path, cost, delay), …] or None if fewer than 3 exist.
        """
        try:
            temp = self.net.copy()
            disjoint_paths = []

            for _ in range(3):
                H = nx.Graph()
                for u, v, data in temp.edges(data=True):
                    if data.get('available_bw', 0) >= flow_bw:
                        H.add_edge(u, v, weight=data['weight'])
                if not nx.has_path(H, src, dst):
                    break

                try:
                    p = next(nx.shortest_simple_paths(H, src, dst, weight='weight'))
                except StopIteration:
                    break

                cost = sum(H[u][v]['weight'] for u, v in zip(p, p[1:]))
                delay = cost * self.DELAY_PER_HOP
                disjoint_paths.append((p, cost, delay))

                for u, v in zip(p, p[1:]):
                    if temp.has_edge(u, v):
                        temp.remove_edge(u, v)

            if len(disjoint_paths) < 3:
                return None

            with open("shortest_paths.txt", "a") as f:
                for idx, (p, c, d) in enumerate(disjoint_paths, start=1):
                    f.write(f"Flow from {src} to {dst} (Eppstein Path {idx}): {p} | "
                            f"Cost: {c} | Delay: {d} ms | BW: {flow_bw}\n")

            return disjoint_paths

        except Exception as e:
            self.logger.error("Eppstein error %s→%s (bw=%d): %s", src, dst, flow_bw, e)
            return None

    def load_link_costs(self):
        """
        Load link costs from 'link_costs.txt'.
        Each line should be in the format: <src> <dst> <cost>
        (Switch names are assumed to be in the form 's<ID>').
        """
        self.link_costs = {}
        try:
            with open('link_costs.txt', 'r') as f:
                for line in f:
                    src, dst, cost = line.strip().split()
                    src_id = int(src[1:])
                    dst_id = int(dst[1:])
                    key = frozenset({src_id, dst_id})
                    self.link_costs[key] = int(cost)
            self.logger.info("Loaded link costs: %s", self.link_costs)
        except Exception as e:
            self.logger.error("Failed to load link_costs.txt: %s", e)

    def plot_topology(self):
        """
        Plot the network topology with edge labels showing link costs and available bandwidth.
        Also, display the current number of active flows.
        """
        plt.figure(figsize=(10, 10))
        pos = nx.spring_layout(self.net, seed=42)
        node_size = 100
        labels = {node: str(node) for node in self.net.nodes()}
        nx.draw_networkx_nodes(self.net, pos, node_color='lightblue', node_size=node_size)
        nx.draw_networkx_labels(self.net, pos, labels=labels, font_size=8)
        edge_colors = []
        for u, v, data in self.net.edges(data=True):
            avail_bw = data.get('available_bw', 0)
            normalized = avail_bw / self.DEFAULT_BANDWIDTH
            color = (1 - normalized, normalized, 0)
            edge_colors.append(color)
        nx.draw_networkx_edges(self.net, pos, edgelist=list(self.net.edges()),
                               edge_color=edge_colors, width=2)
        active_flow_count = len(self.active_flows)
        plt.text(0.05, 0.95, f"Active Flows: {active_flow_count}",
                 transform=plt.gca().transAxes, fontsize=12,
                 verticalalignment='top',
                 bbox=dict(facecolor='white', alpha=0.8, boxstyle='round'))
        plt.title("Network Topology with Available Bandwidth")
        plt.tight_layout()
        plt.savefig("topology.png")
        plt.close()
        self.logger.info("Topology plot saved as topology.png")

    def plot_available_bw_over_time(self):
        """
        Plot a time series of total available bandwidth over monitor cycles.
        """
        plt.figure(figsize=(8, 6))
        plt.plot(self.monitor_history, self.available_bw_history, marker='o', linestyle='-')
        plt.xlabel("Monitor Interaction Count")
        plt.ylabel("Total Available Bandwidth")
        plt.title("Available Bandwidth over Monitor Interactions")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("available_bw_over_time.png")
        plt.close()
        self.logger.info("Available Bandwidth over time plot saved as available_bw_over_time.png")

    def plot_avg_path_cost_over_time(self):
        """
        Plot a time series of average path cost over monitor cycles.
        """
        plt.figure(figsize=(8, 6))
        plt.plot(self.monitor_history, self.avg_path_cost_history, marker='o',
                 linestyle='-', color="green")
        plt.xlabel("Monitor Interaction Count")
        plt.ylabel("Average Path Cost")
        plt.title("Average Path Cost over Monitor Interactions")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("avg_path_cost_over_time.png")
        plt.close()
        self.logger.info("Average Path Cost over time plot saved as avg_path_cost_over_time.png")

    def plot_cost_boxplot(self):
        """
        Create a single figure with three box-plots—one for each
        disjoint path (1st, 2nd, 3rd)—all sharing the same y-axis.
        """
        if not self.flow_history:
            return

        # Gather costs by path index
        costs_by_path = {1: [], 2: [], 3: []}
        for flow in self.flow_history:
            for idx, (_, cost, _) in enumerate(flow.get("disjoint_paths", []), start=1):
                if idx in costs_by_path and cost is not None:
                    costs_by_path[idx].append(cost)

        # If there's no data at all, bail out
        if not any(costs_by_path.values()):
            return

        # Set up 1×3 subplots, sharing the y-axis
        fig, axes = plt.subplots(1, 3, figsize=(12, 6), sharey=True)

        for ax, idx in zip(axes, (1, 2, 3)):
            costs = costs_by_path[idx]
            if costs:
                ax.boxplot(costs)
            else:
                ax.text(0.5, 0.5, "No data", ha="center", va="center")
            ax.set_title(f"Path #{idx}")
            ax.set_xlabel("Disjoint Path")

        # Common y-axis label and overall title
        axes[0].set_ylabel("Path Cost")
        plt.suptitle("Disjoint Path Cost Comparison")
        plt.tight_layout(rect=[0, 0, 1, 0.96])

        # Save and close
        plt.savefig("flow_cost_boxplot_combined.png")
        plt.close()
        self.logger.info(
            "Combined flow cost box plot saved as flow_cost_boxplot_combined.png"
        )

    def plot_bandwidth_boxplot(self):
        """
        Create a box plot for the bandwidth usage of all recorded data flows.
        """
        if not self.flow_history:
            return
        bandwidths = [flow["flow_bw"] for flow in self.flow_history]
        if not bandwidths:
            return
        plt.figure(figsize=(8, 6))
        plt.boxplot(bandwidths)
        plt.ylabel("Bandwidth Used")
        plt.title("Box Plot of Data Flow Bandwidth")
        plt.tight_layout()
        plt.savefig("flow_bandwidth_boxplot.png")
        plt.close()
        self.logger.info("Flow bandwidth box plot saved as flow_bandwidth_boxplot.png")


    def plot_failed_paths_over_time(self):
        """
        Plot the number of flow requests per cycle that could NOT be fulfilled
        (i.e., for which we failed to find 3 separate paths).
        """
        # Nothing to do if we have no data yet
        if not self.monitor_history or not self.failed_path_count_history:
            return

        plt.figure(figsize=(8, 6))
        plt.plot(
            self.monitor_history,
            self.failed_path_count_history,
            marker='o',
            linestyle='-',
            color='red'
        )
        plt.xlabel("Monitor Cycle")
        plt.ylabel("Unfulfilled Flow Requests")
        plt.title("Flows per Cycle with <3 Disjoint Paths Found")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig("failures_over_time.png")
        plt.close()
        self.logger.info("Failures over time plot saved as failures_over_time.png")

    def plot_link_bw_boxplot(self):
        """
        Create a box plot of the current available bandwidth on all links.
        """
        # If there are no edges, do nothing
        if self.net.number_of_edges() == 0:
            return

        # Gather available bandwidth on every link
        avail_bws = [
            data.get('available_bw', 0)
            for u, v, data in self.net.edges(data=True)
        ]
        if not avail_bws:
            return

        plt.figure(figsize=(8, 6))
        plt.boxplot(avail_bws)
        plt.ylabel("Available Bandwidth per Link")
        plt.title("Box Plot of Available Bandwidth Across Links")
        plt.tight_layout()
        plt.savefig("link_bw_boxplot.png")
        plt.close()
        self.logger.info("Link bandwidth box plot saved as link_bw_boxplot.png")

    def plot_link_bw_per_cycle(self):
        """
        Boxplot of link available-bandwidth for each monitor cycle,
        all subplots on one figure.
        """
        if not self.link_bw_cycle_history:
            return

        labels = [str(c) for c in self.monitor_history]
        plt.figure(figsize=(12, 6))
        plt.boxplot(self.link_bw_cycle_history, labels=labels, showfliers=False)
        plt.xlabel("Monitor Cycle")
        plt.ylabel("Available Bandwidth per Link")
        plt.title("Link Available-Bandwidth Distribution by Cycle")
        plt.tight_layout()
        plt.savefig("link_bw_per_cycle_boxplots.png")
        plt.close()
        self.logger.info("Per-cycle link BW boxplots saved as link_bw_per_cycle_boxplots.png")

    def plot_avg_costs_by_path_index(self):
        """
        For each monitor cycle, compute the average cost of
        disjoint path #1, #2, and #3 (across only those flows
        where that path was actually found), and plot them as three lines.
        """
        if not self.flow_history:
            return

        # Ordered list of cycles
        cycles = sorted({flow["creation_cycle"] for flow in self.flow_history})

        avg1, avg2, avg3 = [], [], []

        for cycle in cycles:
            # All flows in this cycle
            flows = [f for f in self.flow_history if f["creation_cycle"] == cycle]

            # Collect only finite costs for each path-index
            c1 = [
                f["disjoint_paths"][0][1]
                for f in flows
                if len(f["disjoint_paths"]) >= 1
                   and f["disjoint_paths"][0][1] is not None
                   and math.isfinite(f["disjoint_paths"][0][1])
            ]
            c2 = [
                f["disjoint_paths"][1][1]
                for f in flows
                if len(f["disjoint_paths"]) >= 2
                   and f["disjoint_paths"][1][1] is not None
                   and math.isfinite(f["disjoint_paths"][1][1])
            ]
            c3 = [
                f["disjoint_paths"][2][1]
                for f in flows
                if len(f["disjoint_paths"]) >= 3
                   and f["disjoint_paths"][2][1] is not None
                   and math.isfinite(f["disjoint_paths"][2][1])
            ]

            # Compute per-cycle averages (nan if no successful paths)
            avg1.append(sum(c1) / len(c1) if c1 else float("nan"))
            avg2.append(sum(c2) / len(c2) if c2 else float("nan"))
            avg3.append(sum(c3) / len(c3) if c3 else float("nan"))

        # Plot all three on one axes
        plt.figure(figsize=(10, 6))
        plt.plot(cycles, avg1, marker="o", linestyle="-", label="Path #1")
        plt.plot(cycles, avg2, marker="^", linestyle="-", label="Path #2")
        plt.plot(cycles, avg3, marker="s", linestyle="-", label="Path #3")
        plt.xlabel("Monitor Cycle")
        plt.ylabel("Average Path Cost")
        plt.title("Average Disjoint Path Costs per Cycle (only successful paths)")
        plt.legend()
        plt.grid(True)
        plt.tight_layout()

        # Save it
        plt.savefig("avg_costs_by_path_index.png")
        plt.close()
        self.logger.info(
            "Avg costs by path index plot saved as avg_costs_by_path_index.png"
        )

    def plot_combined(self):
        """
        Create a combined plot (4x2 grid) of:
         • Available bandwidth over time
         • Average path cost over time
         • Flow bandwidth boxplot
         • Flow cost boxplot
         • Available bandwidth per link (new)
         • Failed paths over time
         • Path algorithm info
        """
        fig, axs = plt.subplots(2, 4, figsize=(24, 12))

        # Row 0, Col 0: Available bandwidth
        axs[0, 0].plot(self.monitor_history, self.available_bw_history, marker='o', linestyle='-')
        axs[0, 0].set_xlabel("Monitor Interaction Count")
        axs[0, 0].set_ylabel("Total Available Bandwidth")
        axs[0, 0].set_title("Available Bandwidth over Time")
        axs[0, 0].grid(True)

        # Row 0, Col 1: Average path cost
        axs[0, 1].plot(self.monitor_history, self.avg_path_cost_history, marker='o', linestyle='-', color="green")
        axs[0, 1].set_xlabel("Monitor Interaction Count")
        axs[0, 1].set_ylabel("Average Path Cost")
        axs[0, 1].set_title("Average Path Cost over Time")
        axs[0, 1].grid(True)

        # Row 1, Col 0: Flow bandwidth boxplot
        if self.flow_history:
            bws = [flow["flow_bw"] for flow in self.flow_history]
            if bws:
                axs[1, 0].boxplot(bws)
                axs[1, 0].set_ylabel("Bandwidth Used")
                axs[1, 0].set_title("Flow Bandwidth Box Plot")
                axs[1, 0].grid(True)
            else:
                axs[1, 0].text(0.5, 0.5, 'No bandwidth data', ha='center')
        else:
            axs[1, 0].text(0.5, 0.5, 'No flow history', ha='center')

        # Row 1, Col 1: Flow cost boxplot
        if self.flow_history:
            costs = [flow["cost"] for flow in self.flow_history if flow["cost"] is not None]
            if costs:
                axs[1, 1].boxplot(costs)
                axs[1, 1].set_ylabel("Flow Costs")
                axs[1, 1].set_title("Flow Cost Box Plot")
                axs[1, 1].grid(True)
            else:
                axs[1, 1].text(0.5, 0.5, 'No cost data', ha='center')
        else:
            axs[1, 1].text(0.5, 0.5, 'No flow history', ha='center')

        # Row 2, Col 0: Link available-bandwidth boxplot (NEW)
        if self.net.number_of_edges() > 0:
            link_bws = [data['available_bw'] for u, v, data in self.net.edges(data=True)]
            if link_bws:
                axs[1, 2].boxplot(link_bws)
                axs[1, 2].set_ylabel("Available BW per Link")
                axs[1, 2].set_title("Link Bandwidth Distribution")
                axs[1, 2].grid(True)
            else:
                axs[1, 2].text(0.5, 0.5, 'No link data', ha='center')
        else:
            axs[1, 2].text(0.5, 0.5, 'No links', ha='center')

        # Row 2, Col 1: Failed paths over time
        axs[0, 2].plot(self.monitor_history, self.failed_path_count_history, marker='o', linestyle='-', color="red")
        axs[0, 2].set_xlabel("Monitor Interaction Count")
        axs[0, 2].set_ylabel("Failed Path Count")
        axs[0, 2].set_title("Failed Paths over Time")
        axs[0, 2].grid(True)

        # Row 3, Col 0: Path algorithm info
        axs[0, 3].axis('off')
        axs[0, 3].text(
            0.5, 0.5,
            f"Path Algorithm: {self.path_algorithm}",
            ha='center', va='center',
            fontsize=12,
            bbox=dict(facecolor='white', alpha=0.8, boxstyle='round')
        )

        # Row 3, Col 1: (empty or future use)
        axs[1, 3].axis('off')

        plt.tight_layout()
        plt.savefig("combined_plots.png")
        plt.close()
        self.logger.info("Combined plot (with link BW boxplot) saved as combined_plots.png")


    def add_data_flow(self, src, dst, flow_bw):
        """
        Simulate adding a new data flow…
        Count a failure if ANY one of the three paths was not found.
        """
        paths = self.compute_flow_path(src, dst, flow_bw)

        # Fail if fewer than 3 valid paths
        if (paths is None
            or len(paths) < 3
            or any(math.isinf(p[1]) for p in paths[:3])):
            self.current_cycle_failures += 1
            return

        # All 3 paths exist — consume bandwidth on each path
        for path, cost, delay in paths[:3]:
            for u, v in zip(path, path[1:]):
                # subtract bandwidth on every link of each path
                self.net[u][v]['available_bw'] = max(
                    0, self.net[u][v]['available_bw'] - flow_bw
                )

        # Record stats for the primary path (used for routing/installing rules)
        primary_path, cost, delay = paths[0]
        self.current_cycle_costs.append(cost)

        flow_record = {
            "src": src,
            "dst": dst,
            "flow_bw": flow_bw,
            "primary_path": primary_path,
            "disjoint_paths": paths,
            "creation_cycle": self.monitor_count,
            "cost": cost,
            "delay": delay
        }
        self.active_flows.append(flow_record)
        self.flow_history.append(flow_record.copy())

    @set_ev_cls(event.EventSwitchEnter)
    def switch_enter_handler(self, ev):
        """
        When a new switch enters the network, add its datapath ID as a node.
        """
        for sw in ev.switches:
            dpid = sw.dp.id
            if not self.net.has_node(dpid):
                self.net.add_node(dpid)
                self.logger.info("Switch %s entered.", dpid)

    @set_ev_cls(event.EventLinkAdd)
    def link_add_handler(self, ev):
        """
        When a link is discovered and is defined in link_costs.txt, add it to the network graph.
        Each edge is annotated with its cost, total bandwidth, and available bandwidth.
        """
        link = ev.link
        src_dpid = link.src.dpid
        dst_dpid = link.dst.dpid
        key = frozenset({src_dpid, dst_dpid})
        if key not in self.link_costs:
            return

        if not self.net.has_node(src_dpid):
            self.net.add_node(src_dpid)
        if not self.net.has_node(dst_dpid):
            self.net.add_node(dst_dpid)

        cost = self.link_costs[key]
        self.net.add_edge(src_dpid, dst_dpid, weight=cost,
                          bandwidth=self.DEFAULT_BANDWIDTH,
                          available_bw=self.DEFAULT_BANDWIDTH)
        self.link_ports[(src_dpid, dst_dpid)] = link.src.port_no
        self.link_ports[(dst_dpid, src_dpid)] = link.dst.port_no

    @set_ev_cls(ofp_event.EventOFPSwitchFeatures, CONFIG_DISPATCHER)
    def switch_features_handler(self, ev):
        """
        Install the table-miss flow entry.
        """
        datapath = ev.msg.datapath
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser

        match = parser.OFPMatch()
        actions = [parser.OFPActionOutput(ofproto.OFPP_CONTROLLER,
                                          ofproto.OFPCML_NO_BUFFER)]
        inst = [parser.OFPInstructionActions(ofproto.OFPIT_APPLY_ACTIONS,
                                             actions)]
        mod = parser.OFPFlowMod(datapath=datapath, priority=0,
                                match=match, instructions=inst)
        datapath.send_msg(mod)

    @set_ev_cls(ofp_event.EventOFPPacketIn, MAIN_DISPATCHER)
    def packet_in_handler(self, ev):
        """
        Handle incoming packets:
         - Learn host locations.
         - If the destination host is known, compute a path using the base graph.
         - Otherwise, flood the packet.
        """
        msg = ev.msg
        datapath = msg.datapath
        dpid = datapath.id
        ofproto = datapath.ofproto
        parser = datapath.ofproto_parser

        in_port = msg.match['in_port']
        pkt = packet.Packet(msg.data)
        eth = pkt.get_protocol(ethernet.ethernet)
        if eth is None:
            return

        src_mac = eth.src
        dst_mac = eth.dst

        if dst_mac in self.hosts:
            dest_switch, dest_port = self.hosts[dst_mac]
            try:
                path = nx.dijkstra_path(self.net, dpid, dest_switch, weight='weight')
                self.logger.info("Computed path from %s to %s: %s", dpid, dest_switch, path)
                if len(path) > 1:
                    next_hop = path[1]
                    out_port = self.link_ports.get((dpid, next_hop), ofproto.OFPP_FLOOD)
                else:
                    out_port = dest_port
            except nx.NetworkXNoPath:
                self.logger.info("No path from switch %s to host %s; flooding", dpid, dst_mac)
                out_port = ofproto.OFPP_FLOOD
        else:
            out_port = ofproto.OFPP_FLOOD

        actions = [parser.OFPActionOutput(out_port)]
        out = parser.OFPPacketOut(datapath=datapath, buffer_id=msg.buffer_id,
                                  in_port=in_port, actions=actions, data=msg.data)
        datapath.send_msg(out)